---

- name: add {{ http_user }} user
  user:
    name: "{{ http_user }}"
    shell: /bin/bash
    comment: "Apache User"
    home: /home/{{ http_user }}
    groups: www-data
    append: 'yes'

- name: Create document directory for {{ http_host }}
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ http_user }}"
    group: www-data
    mode: '0755'

- name: Set up Apache virtualhost for {{ http_host }}
  template:
    src: "config/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
    owner: root
    mode: '0644'
  notify: Restart Apache

- name: Enable new {{ http_host }}
  command: /usr/sbin/a2ensite {{ http_conf }}
  notify: Restart Apache

- name: Disable default Apache site
  command: /usr/sbin/a2dissite 000-default.conf
  notify: Restart Apache

- name: php info page
  template:
    src: "config/info.php.j2"
    dest: "/var/www/{{ http_host }}/info.php"
    owner: "{{ http_user }}"
    group: www-data
    mode: '644'

- name: simple html page
  template:
    src: "config/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"
    owner: "{{ http_user }}"
    group: www-data
    mode: '644'
