---

- name: enable mysql service
  service:
    name: mysql
    state: started
    enabled: 'yes'

- name: Save root password in .my.cnf
  become: 'yes'
  template:
    src: config/root_cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: Set mysql root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Removes all anonymous users
  mysql_user:
    name: ''
    host_all: 'yes'
    state: 'absent'
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
