---
- name: install packages
  apt:
    name:
      - apache2
      - mysql-server
      - python3-pymysql
      - php
      - php-mysql
      - libapache2-mod-php
    state: present
    cache_valid_time: 3600
